package com.administrationsystem.dentalClinic.models.dentist;

import java.util.ArrayList;
import java.util.Arrays;

public class DentistManager
{

    private static DentistManager dentistManager;
    private ArrayList<String> detailsDentist;
    public DentistManager()
    {

        detailsDentist = new ArrayList<>(Arrays.asList("dentistId","name","surname","username","email","address","telephone"));

    }



    public Dentist createDentist(Dentist dentist) {
        Dentist newDentist = new Dentist();
        for(String detail: detailsDentist)
        {

            setDetail(detail, newDentist, dentist);

        }
        return newDentist;

    }

    public void setDetail(String detail, Dentist dentist, Dentist dentistData)
    {

        switch (detail)
        {
            case "name" -> dentist.setName(dentistData.getName());
            case "surname" -> dentist.setSurname(dentistData.getSurname());
            case "username" -> dentist.setUsername(dentistData.getUsername());
            case "email" -> dentist.setEmail(dentistData.getEmail());
            case "dentistId" -> dentist.setDentistId(dentistData.getDentistId());
            case "telephone" -> dentist.setTelephone(dentistData.getTelephone());
            case "address" -> dentist.setAddress(dentistData.getAddress());
        }
    }

    public Dentist updateDentist(Dentist oldDentist, Dentist newDentist) {

        for(String detail: detailsDentist)
        {
            if(!detail.equals("dentistId")) {
                setDetail(detail, oldDentist, newDentist); //dentistId is autogenerated
            }
        }
        return newDentist;

    }

    public static DentistManager getInstance() {
        if (dentistManager == null) {
            dentistManager = new DentistManager();
        }
        return dentistManager;
    }
}
